### ISSUE TITLE
The licensing for Beckhoff is transparent

### ISSUE THREAD

**Issue by RalphKoettlitz** [SASE-Space/ot-openness-comparison#6]
The licensing for Beckhoff  is depending on HW and the used runtime features. The system is easy to understand and can be configured in the project. Even software developers can build their licenses based on the system Beckhoff has developed.

**Comment by zantiu** [comment]
Do you have an official link to the licensing?

**Comment by shanereetz** [comment]
Here are official, and non-official but useful docs on the licensing strategy. I am having trouble finding specific prices, other than forums and reddit posts.

General page on licensing
https://www.beckhoff.com/en-us/products/automation/twincat/twincat-3-licensing/

As Ralph mentioned, HW can influence the runtime license price:
`The price of TwinCAT 3 runtime licenses depends on the performance of the control computer employed. The performance is subdivided into so-called` [platform levels](https://www.beckhoff.com/en-us/products/automation/twincat/twincat-3-platforms/).

More detailed answer about "platform level" implications
`Beckhoffs licensing model for TwinCAT and all the supplements is built on a model based on [platform levels](https://www.beckhoff.com/english.asp?twincat/twincat-3-platform-classification.htm). It starts on the platform level of 10 for basic single-core low-performance CPUs, all the way to platform level 94, for 64 core CPUs. The higher the platform level, the higher the cost of the license. The platform level 90 to 94 is for everything that is not Beckhoff hardware. The IP67 PC we found had the exact same CPU as a Beckhoff PLC with performance class 40, but because it was not a Beckhoff PLC, it was classed as performance class 90. If you are at level 90, licenses get really expensive considering we were using a low-power 2 core CPU. Because of the cost of all licenses, it was not possible to motivate us to run TwinCAT.`
https://alltwincat.com/2020/06/15/the-five-best-and-worst-things-with-twincat/

`Various functions extending beyond pure PLC programming (TwinCAT 3 functions) and all TwinCAT 3 runtime licenses are chargeable, however.`
https://infosys.beckhoff.com/english.php?content=../content/1033/tc3_licensing/920379275.html&id=

TwinCAT itself is available for free via forever renewable 7-day trial licenses: `The free TwinCAT 3 download enables a straightforward, unbureaucratic acquisition for education and training purposes. The TwinCAT 3 development environment can be installed on any number of development computers. The [7-day trial license](https://infosys.beckhoff.com/content/1033/tc3_licensing/921947147.html) for TwinCAT 3 products, which can be renewed over and over again, enables TwinCAT functionalities to be used in a straightforward and cost-effective manner in the lab.`

**Comment by zantiu** [comment]
An example of transparent licensing:
https://inductiveautomation.com/pricing/ignition

**Comment by TheColonel2688** [comment]
Ummmm I see no prices anywhere on there website.... so "Open and Transparent"?? 

"I don't think that means what you think it means"

**Comment by zantiu** [comment]
Transparency have have different interpretations, which is fine.
The requirement here is to have at least the basic list prices available.

**Comment by TheColonel2688** [comment]
Obviously it doesn't always, since thst is not how other platforms work

**Comment by zantiu** [comment]
Price transparency strategy is actually a big topic, and an important thing to decide for the vendors. It creates a lot of friction in many situations if it's not in place. There's a reason why companies like Codesys and Ignition decide to do this. There's also a correlation between pricing transparency and innovation. Anyway good to have the column available for people who think it's important.
